/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DesignaryBlauContainer {
    }
    interface DesignaryButton {
    }
    interface DesignaryCards {
    }
    interface DesignaryContact {
        "containerTitle": string;
    }
    interface DesignaryEmployee {
        "icon1": string;
        "icon2": string;
        "icon3": string;
        "imageurl": string;
        "job": string;
        "name": string;
    }
    interface DesignaryEmployeeContainer {
        "containerTitle": string;
    }
    interface DesignaryFooter {
    }
    interface DesignaryGallery {
    }
    interface DesignaryGreyContainer {
        "containerTitle": string;
    }
    interface DesignaryHeaderHero_section {
    }
    interface DesignaryNewsletter {
    }
    interface DesignarySection {
    }
    interface DesignarySlider {
    }
    interface DesignarySlideshow {
    }
    interface DesignaryTestimonial {
        "brand": string;
        "person": string;
        "text": string;
    }
    interface ExampleComponent {
        "exampleProp": string;
        "exampleToUpperCase": () => Promise<void>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDesignaryBlauContainerElement extends Components.DesignaryBlauContainer, HTMLStencilElement {
    }
    var HTMLDesignaryBlauContainerElement: {
        prototype: HTMLDesignaryBlauContainerElement;
        new (): HTMLDesignaryBlauContainerElement;
    };
    interface HTMLDesignaryButtonElement extends Components.DesignaryButton, HTMLStencilElement {
    }
    var HTMLDesignaryButtonElement: {
        prototype: HTMLDesignaryButtonElement;
        new (): HTMLDesignaryButtonElement;
    };
    interface HTMLDesignaryCardsElement extends Components.DesignaryCards, HTMLStencilElement {
    }
    var HTMLDesignaryCardsElement: {
        prototype: HTMLDesignaryCardsElement;
        new (): HTMLDesignaryCardsElement;
    };
    interface HTMLDesignaryContactElement extends Components.DesignaryContact, HTMLStencilElement {
    }
    var HTMLDesignaryContactElement: {
        prototype: HTMLDesignaryContactElement;
        new (): HTMLDesignaryContactElement;
    };
    interface HTMLDesignaryEmployeeElement extends Components.DesignaryEmployee, HTMLStencilElement {
    }
    var HTMLDesignaryEmployeeElement: {
        prototype: HTMLDesignaryEmployeeElement;
        new (): HTMLDesignaryEmployeeElement;
    };
    interface HTMLDesignaryEmployeeContainerElement extends Components.DesignaryEmployeeContainer, HTMLStencilElement {
    }
    var HTMLDesignaryEmployeeContainerElement: {
        prototype: HTMLDesignaryEmployeeContainerElement;
        new (): HTMLDesignaryEmployeeContainerElement;
    };
    interface HTMLDesignaryFooterElement extends Components.DesignaryFooter, HTMLStencilElement {
    }
    var HTMLDesignaryFooterElement: {
        prototype: HTMLDesignaryFooterElement;
        new (): HTMLDesignaryFooterElement;
    };
    interface HTMLDesignaryGalleryElement extends Components.DesignaryGallery, HTMLStencilElement {
    }
    var HTMLDesignaryGalleryElement: {
        prototype: HTMLDesignaryGalleryElement;
        new (): HTMLDesignaryGalleryElement;
    };
    interface HTMLDesignaryGreyContainerElement extends Components.DesignaryGreyContainer, HTMLStencilElement {
    }
    var HTMLDesignaryGreyContainerElement: {
        prototype: HTMLDesignaryGreyContainerElement;
        new (): HTMLDesignaryGreyContainerElement;
    };
    interface HTMLDesignaryHeaderHero_sectionElement extends Components.DesignaryHeaderHero_section, HTMLStencilElement {
    }
    var HTMLDesignaryHeaderHero_sectionElement: {
        prototype: HTMLDesignaryHeaderHero_sectionElement;
        new (): HTMLDesignaryHeaderHero_sectionElement;
    };
    interface HTMLDesignaryNewsletterElement extends Components.DesignaryNewsletter, HTMLStencilElement {
    }
    var HTMLDesignaryNewsletterElement: {
        prototype: HTMLDesignaryNewsletterElement;
        new (): HTMLDesignaryNewsletterElement;
    };
    interface HTMLDesignarySectionElement extends Components.DesignarySection, HTMLStencilElement {
    }
    var HTMLDesignarySectionElement: {
        prototype: HTMLDesignarySectionElement;
        new (): HTMLDesignarySectionElement;
    };
    interface HTMLDesignarySliderElement extends Components.DesignarySlider, HTMLStencilElement {
    }
    var HTMLDesignarySliderElement: {
        prototype: HTMLDesignarySliderElement;
        new (): HTMLDesignarySliderElement;
    };
    interface HTMLDesignarySlideshowElement extends Components.DesignarySlideshow, HTMLStencilElement {
    }
    var HTMLDesignarySlideshowElement: {
        prototype: HTMLDesignarySlideshowElement;
        new (): HTMLDesignarySlideshowElement;
    };
    interface HTMLDesignaryTestimonialElement extends Components.DesignaryTestimonial, HTMLStencilElement {
    }
    var HTMLDesignaryTestimonialElement: {
        prototype: HTMLDesignaryTestimonialElement;
        new (): HTMLDesignaryTestimonialElement;
    };
    interface HTMLExampleComponentElement extends Components.ExampleComponent, HTMLStencilElement {
    }
    var HTMLExampleComponentElement: {
        prototype: HTMLExampleComponentElement;
        new (): HTMLExampleComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "designary-blau-container": HTMLDesignaryBlauContainerElement;
        "designary-button": HTMLDesignaryButtonElement;
        "designary-cards": HTMLDesignaryCardsElement;
        "designary-contact": HTMLDesignaryContactElement;
        "designary-employee": HTMLDesignaryEmployeeElement;
        "designary-employee-container": HTMLDesignaryEmployeeContainerElement;
        "designary-footer": HTMLDesignaryFooterElement;
        "designary-gallery": HTMLDesignaryGalleryElement;
        "designary-grey-container": HTMLDesignaryGreyContainerElement;
        "designary-header-hero_section": HTMLDesignaryHeaderHero_sectionElement;
        "designary-newsletter": HTMLDesignaryNewsletterElement;
        "designary-section": HTMLDesignarySectionElement;
        "designary-slider": HTMLDesignarySliderElement;
        "designary-slideshow": HTMLDesignarySlideshowElement;
        "designary-testimonial": HTMLDesignaryTestimonialElement;
        "example-component": HTMLExampleComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DesignaryBlauContainer {
    }
    interface DesignaryButton {
    }
    interface DesignaryCards {
    }
    interface DesignaryContact {
        "containerTitle"?: string;
    }
    interface DesignaryEmployee {
        "icon1"?: string;
        "icon2"?: string;
        "icon3"?: string;
        "imageurl"?: string;
        "job"?: string;
        "name"?: string;
    }
    interface DesignaryEmployeeContainer {
        "containerTitle"?: string;
    }
    interface DesignaryFooter {
    }
    interface DesignaryGallery {
    }
    interface DesignaryGreyContainer {
        "containerTitle"?: string;
    }
    interface DesignaryHeaderHero_section {
    }
    interface DesignaryNewsletter {
    }
    interface DesignarySection {
    }
    interface DesignarySlider {
    }
    interface DesignarySlideshow {
    }
    interface DesignaryTestimonial {
        "brand"?: string;
        "person"?: string;
        "text"?: string;
    }
    interface ExampleComponent {
        "exampleProp"?: string;
        "onExampleEvent"?: (event: CustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "designary-blau-container": DesignaryBlauContainer;
        "designary-button": DesignaryButton;
        "designary-cards": DesignaryCards;
        "designary-contact": DesignaryContact;
        "designary-employee": DesignaryEmployee;
        "designary-employee-container": DesignaryEmployeeContainer;
        "designary-footer": DesignaryFooter;
        "designary-gallery": DesignaryGallery;
        "designary-grey-container": DesignaryGreyContainer;
        "designary-header-hero_section": DesignaryHeaderHero_section;
        "designary-newsletter": DesignaryNewsletter;
        "designary-section": DesignarySection;
        "designary-slider": DesignarySlider;
        "designary-slideshow": DesignarySlideshow;
        "designary-testimonial": DesignaryTestimonial;
        "example-component": ExampleComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "designary-blau-container": LocalJSX.DesignaryBlauContainer & JSXBase.HTMLAttributes<HTMLDesignaryBlauContainerElement>;
            "designary-button": LocalJSX.DesignaryButton & JSXBase.HTMLAttributes<HTMLDesignaryButtonElement>;
            "designary-cards": LocalJSX.DesignaryCards & JSXBase.HTMLAttributes<HTMLDesignaryCardsElement>;
            "designary-contact": LocalJSX.DesignaryContact & JSXBase.HTMLAttributes<HTMLDesignaryContactElement>;
            "designary-employee": LocalJSX.DesignaryEmployee & JSXBase.HTMLAttributes<HTMLDesignaryEmployeeElement>;
            "designary-employee-container": LocalJSX.DesignaryEmployeeContainer & JSXBase.HTMLAttributes<HTMLDesignaryEmployeeContainerElement>;
            "designary-footer": LocalJSX.DesignaryFooter & JSXBase.HTMLAttributes<HTMLDesignaryFooterElement>;
            "designary-gallery": LocalJSX.DesignaryGallery & JSXBase.HTMLAttributes<HTMLDesignaryGalleryElement>;
            "designary-grey-container": LocalJSX.DesignaryGreyContainer & JSXBase.HTMLAttributes<HTMLDesignaryGreyContainerElement>;
            "designary-header-hero_section": LocalJSX.DesignaryHeaderHero_section & JSXBase.HTMLAttributes<HTMLDesignaryHeaderHero_sectionElement>;
            "designary-newsletter": LocalJSX.DesignaryNewsletter & JSXBase.HTMLAttributes<HTMLDesignaryNewsletterElement>;
            "designary-section": LocalJSX.DesignarySection & JSXBase.HTMLAttributes<HTMLDesignarySectionElement>;
            "designary-slider": LocalJSX.DesignarySlider & JSXBase.HTMLAttributes<HTMLDesignarySliderElement>;
            "designary-slideshow": LocalJSX.DesignarySlideshow & JSXBase.HTMLAttributes<HTMLDesignarySlideshowElement>;
            "designary-testimonial": LocalJSX.DesignaryTestimonial & JSXBase.HTMLAttributes<HTMLDesignaryTestimonialElement>;
            "example-component": LocalJSX.ExampleComponent & JSXBase.HTMLAttributes<HTMLExampleComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
