/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DesignaryCards {
    }
    interface DesignaryContact {
        "containerTitle": string;
    }
    interface DesignaryContact2 {
    }
    interface DesignaryEmployee {
        "test": String;
    }
    interface DesignaryGallery {
    }
    interface DesignaryGreyContainer {
        "containerTitle": string;
    }
    interface DesignarySlider {
    }
    interface DesignaryTestimonial {
        "person": string;
        "text": string;
    }
    interface DesigneryCards {
    }
    interface ExampleComponent {
        "exampleProp": string;
        "exampleToUpperCase": () => Promise<void>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDesignaryCardsElement extends Components.DesignaryCards, HTMLStencilElement {
    }
    var HTMLDesignaryCardsElement: {
        prototype: HTMLDesignaryCardsElement;
        new (): HTMLDesignaryCardsElement;
    };
    interface HTMLDesignaryContactElement extends Components.DesignaryContact, HTMLStencilElement {
    }
    var HTMLDesignaryContactElement: {
        prototype: HTMLDesignaryContactElement;
        new (): HTMLDesignaryContactElement;
    };
    interface HTMLDesignaryContact2Element extends Components.DesignaryContact2, HTMLStencilElement {
    }
    var HTMLDesignaryContact2Element: {
        prototype: HTMLDesignaryContact2Element;
        new (): HTMLDesignaryContact2Element;
    };
    interface HTMLDesignaryEmployeeElement extends Components.DesignaryEmployee, HTMLStencilElement {
    }
    var HTMLDesignaryEmployeeElement: {
        prototype: HTMLDesignaryEmployeeElement;
        new (): HTMLDesignaryEmployeeElement;
    };
    interface HTMLDesignaryGalleryElement extends Components.DesignaryGallery, HTMLStencilElement {
    }
    var HTMLDesignaryGalleryElement: {
        prototype: HTMLDesignaryGalleryElement;
        new (): HTMLDesignaryGalleryElement;
    };
    interface HTMLDesignaryGreyContainerElement extends Components.DesignaryGreyContainer, HTMLStencilElement {
    }
    var HTMLDesignaryGreyContainerElement: {
        prototype: HTMLDesignaryGreyContainerElement;
        new (): HTMLDesignaryGreyContainerElement;
    };
    interface HTMLDesignarySliderElement extends Components.DesignarySlider, HTMLStencilElement {
    }
    var HTMLDesignarySliderElement: {
        prototype: HTMLDesignarySliderElement;
        new (): HTMLDesignarySliderElement;
    };
    interface HTMLDesignaryTestimonialElement extends Components.DesignaryTestimonial, HTMLStencilElement {
    }
    var HTMLDesignaryTestimonialElement: {
        prototype: HTMLDesignaryTestimonialElement;
        new (): HTMLDesignaryTestimonialElement;
    };
    interface HTMLDesigneryCardsElement extends Components.DesigneryCards, HTMLStencilElement {
    }
    var HTMLDesigneryCardsElement: {
        prototype: HTMLDesigneryCardsElement;
        new (): HTMLDesigneryCardsElement;
    };
    interface HTMLExampleComponentElement extends Components.ExampleComponent, HTMLStencilElement {
    }
    var HTMLExampleComponentElement: {
        prototype: HTMLExampleComponentElement;
        new (): HTMLExampleComponentElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "designary-cards": HTMLDesignaryCardsElement;
        "designary-contact": HTMLDesignaryContactElement;
        "designary-contact2": HTMLDesignaryContact2Element;
        "designary-employee": HTMLDesignaryEmployeeElement;
        "designary-gallery": HTMLDesignaryGalleryElement;
        "designary-grey-container": HTMLDesignaryGreyContainerElement;
        "designary-slider": HTMLDesignarySliderElement;
        "designary-testimonial": HTMLDesignaryTestimonialElement;
        "designery-cards": HTMLDesigneryCardsElement;
        "example-component": HTMLExampleComponentElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface DesignaryCards {
    }
    interface DesignaryContact {
        "containerTitle"?: string;
    }
    interface DesignaryContact2 {
    }
    interface DesignaryEmployee {
        "test"?: String;
    }
    interface DesignaryGallery {
    }
    interface DesignaryGreyContainer {
        "containerTitle"?: string;
    }
    interface DesignarySlider {
    }
    interface DesignaryTestimonial {
        "person"?: string;
        "text"?: string;
    }
    interface DesigneryCards {
    }
    interface ExampleComponent {
        "exampleProp"?: string;
        "onExampleEvent"?: (event: CustomEvent<string>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "designary-cards": DesignaryCards;
        "designary-contact": DesignaryContact;
        "designary-contact2": DesignaryContact2;
        "designary-employee": DesignaryEmployee;
        "designary-gallery": DesignaryGallery;
        "designary-grey-container": DesignaryGreyContainer;
        "designary-slider": DesignarySlider;
        "designary-testimonial": DesignaryTestimonial;
        "designery-cards": DesigneryCards;
        "example-component": ExampleComponent;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "designary-cards": LocalJSX.DesignaryCards & JSXBase.HTMLAttributes<HTMLDesignaryCardsElement>;
            "designary-contact": LocalJSX.DesignaryContact & JSXBase.HTMLAttributes<HTMLDesignaryContactElement>;
            "designary-contact2": LocalJSX.DesignaryContact2 & JSXBase.HTMLAttributes<HTMLDesignaryContact2Element>;
            "designary-employee": LocalJSX.DesignaryEmployee & JSXBase.HTMLAttributes<HTMLDesignaryEmployeeElement>;
            "designary-gallery": LocalJSX.DesignaryGallery & JSXBase.HTMLAttributes<HTMLDesignaryGalleryElement>;
            "designary-grey-container": LocalJSX.DesignaryGreyContainer & JSXBase.HTMLAttributes<HTMLDesignaryGreyContainerElement>;
            "designary-slider": LocalJSX.DesignarySlider & JSXBase.HTMLAttributes<HTMLDesignarySliderElement>;
            "designary-testimonial": LocalJSX.DesignaryTestimonial & JSXBase.HTMLAttributes<HTMLDesignaryTestimonialElement>;
            "designery-cards": LocalJSX.DesigneryCards & JSXBase.HTMLAttributes<HTMLDesigneryCardsElement>;
            "example-component": LocalJSX.ExampleComponent & JSXBase.HTMLAttributes<HTMLExampleComponentElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
